name: qt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7.0
  - glew=2.1.0
  - glib=2.68.4
  - pip=21.0.1
  - python=3.11.7
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pip:
      - absl-py==2.0.0
      - cython==0.29.37
      - dm-control==1.0.8
      - easydict==1.9
      - einops==0.7.0
      - ffmpeg==1.4
      - glfw==2.6.4
      - gym==0.21.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - kornia==0.7.1
      - git+https://github.com/Farama-Foundation/Metaworld.git@04be337a12305e393c0caf0cbf5ec7755c7c8feb
      - moviepy==1.0.3
      - mujoco==2.3.1  
      - mujoco-py==2.1.2.14
      - numpy==1.23.5
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - pandas==2.1.4
      - patchelf==0.17.2.1
      - sapien==2.2.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - setuptools==66.1.1
      - submitit==1.5.1
      - termcolor==2.4.0
      - torchrl-nightly==2024.3.26  
      - tqdm==4.66.1
      - wandb==0.16.2
      - wheel==0.38.0